services:
  - type: web
    name: puppeteer-server
    env: node
    buildCommand: ./render-build.sh
    startCommand: node puppeteer-server.js
    plan: starter
    healthCheckPath: /
    autoDeploy: true
